//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Markup.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMarkupListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MarkupBaseListener : IMarkupListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.markup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMarkup([NotNull] MarkupParser.MarkupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.markup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMarkup([NotNull] MarkupParser.MarkupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] MarkupParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] MarkupParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] MarkupParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] MarkupParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.bold"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBold([NotNull] MarkupParser.BoldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.bold"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBold([NotNull] MarkupParser.BoldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.italic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItalic([NotNull] MarkupParser.ItalicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.italic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItalic([NotNull] MarkupParser.ItalicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor([NotNull] MarkupParser.ColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor([NotNull] MarkupParser.ColorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.colorcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColorcode([NotNull] MarkupParser.ColorcodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.colorcode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColorcode([NotNull] MarkupParser.ColorcodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.unmatched_bold"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnmatched_bold([NotNull] MarkupParser.Unmatched_boldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.unmatched_bold"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnmatched_bold([NotNull] MarkupParser.Unmatched_boldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.unmatched_italic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnmatched_italic([NotNull] MarkupParser.Unmatched_italicContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.unmatched_italic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnmatched_italic([NotNull] MarkupParser.Unmatched_italicContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MarkupParser.unmatched_color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnmatched_color([NotNull] MarkupParser.Unmatched_colorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MarkupParser.unmatched_color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnmatched_color([NotNull] MarkupParser.Unmatched_colorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
